require_relative '../../../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityKeepAwake', :path => '../../../../node_modules/@capacitor-community/keep-awake'
  pod 'CapacitorCommunitySafeArea', :path => '../../../../node_modules/@capacitor-community/safe-area'
  pod 'CapacitorCommunityScreenBrightness', :path => '../../../../node_modules/@capacitor-community/screen-brightness'
  pod 'CapacitorApp', :path => '../../../../node_modules/@capacitor/app'
  pod 'CapacitorHaptics', :path => '../../../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../../../node_modules/@capacitor/keyboard'
  pod 'CapacitorPreferences', :path => '../../../../node_modules/@capacitor/preferences'
  pod 'CapacitorPushNotifications', :path => '../../../../node_modules/@capacitor/push-notifications'
  pod 'CapacitorShare', :path => '../../../../node_modules/@capacitor/share'
  pod 'CapacitorStatusBar', :path => '../../../../node_modules/@capacitor/status-bar'
  pod 'CapgoCapacitorUpdater', :path => '../../../../node_modules/@capgo/capacitor-updater'
  pod 'CapgoInappbrowser', :path => '../../../../node_modules/@capgo/inappbrowser'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'FirebaseMessaging'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
